name: web

x-valkey-base: &valkey-base
  image: docker.io/bitnami/valkey-cluster:latest

networks:
  spider:
    driver: bridge

volumes:
  spider:
    driver: local

services:
  spider:
    build:
      context: .
      dockerfile: Dockerfile
    image: spider
    container_name: spider
    depends_on:
      valkey-0:
        condition: service_healthy
    networks:
      - spider
    ports:
      - 8000:8000
    # volumes:
    #   - type: bind
    #     source: ./spider
    #     target: /app

  postgresql:
    image: 'bitnami/postgresql:latest'
    networks:
      - spider
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=airflow
      - POSTGRES_USER=airflow_user
      - POSTGRES_PASSWORD=airflow_password

  airflow:
    image: bitnami/airflow:latest
    networks:
      - spider
    ports:
      - 8080:8080
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow_user
      - AIRFLOW_DATABASE_PASSWORD=airflow_password
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
  valkey-0:
    <<: *valkey-base
    container_name: valkey-0
    hostname: valkey
    networks:
      - spider
    # volumes:
    #   - valkey-0:/bitnami/valkey/data
    ports:
      - 6379:6379
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_USERNAME: bitnami
      REDISCLI_AUTH: bitnami
      VALKEY_CLUSTER_REPLICAS: 1
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5
      VALKEY_CLUSTER_CREATOR: yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 20

  valkey-1:
    <<: *valkey-base
    container_name: valkey-1
    networks:
      - spider
    ports:
      - 6380:6380
    # volumes:
    #   - valkey-1:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-2:
    <<: *valkey-base
    container_name: valkey-2
    networks:
      - spider
    ports:
      - 6381:6381
    # volumes:
    #   - valkey-2:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-3:
    <<: *valkey-base
    container_name: valkey-3
    networks:
      - spider
    ports:
      - 6382:6382
    # volumes:
    #   - valkey-3:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-4:
    <<: *valkey-base
    container_name: valkey-4
    networks:
      - spider
    ports:
      - 6383:6383
    # volumes:
    #   - valkey-4:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-5:
    <<: *valkey-base
    container_name: valkey-5
    networks:
      - spider
    ports:
      - 6384:6384
    # volumes:
    #   - valkey-5:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5
