name: web

x-valkey-base: &valkey-base
  image: docker.io/bitnami/valkey-cluster:latest

networks:
  spider:
    driver: bridge

volumes:
  spider:
    driver: local

services:
  spider:
    build:
      context: .
      dockerfile: Dockerfile
    image: spider
    container_name: spider
    depends_on:
      valkey-0:
        condition: service_healthy
    networks:
      - spider
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./spider
        target: /home/worker/spider

  valkey-0:
    <<: *valkey-base
    container_name: valkey-0
    hostname: valkey
    networks:
      - spider
    # volumes:
    #   - valkey-0:/bitnami/valkey/data
    ports:
      - 6379:6379
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_USERNAME: bitnami
      REDISCLI_AUTH: bitnami
      VALKEY_CLUSTER_REPLICAS: 1
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5
      VALKEY_CLUSTER_CREATOR: yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 20

  valkey-1:
    <<: *valkey-base
    container_name: valkey-1
    networks:
      - spider
    ports:
      - 6380:6380
    # volumes:
    #   - valkey-1:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-2:
    <<: *valkey-base
    container_name: valkey-2
    networks:
      - spider
    ports:
      - 6381:6381
    # volumes:
    #   - valkey-2:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-3:
    <<: *valkey-base
    container_name: valkey-3
    networks:
      - spider
    ports:
      - 6382:6382
    # volumes:
    #   - valkey-3:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-4:
    <<: *valkey-base
    container_name: valkey-4
    networks:
      - spider
    ports:
      - 6383:6383
    # volumes:
    #   - valkey-4:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5

  valkey-5:
    <<: *valkey-base
    container_name: valkey-5
    networks:
      - spider
    ports:
      - 6384:6384
    # volumes:
    #   - valkey-5:/bitnami/valkey/data
    environment:
      VALKEY_PASSWORD: bitnami
      VALKEY_NODES: valkey-0 valkey-1 valkey-2 valkey-3 valkey-4 valkey-5
